### ISSUE TITLE
support for ros2 galactic 

### ISSUE THREAD

**Issue by 3mrrrx** [youtalk/dynamixel_control#15]
Hallo on building with ros2-galatic i am getting this error:

cmds:
`
source /opt/ros/galactic/setup.bash
mkdir -p ~/ros/galactic && cd ~/ros/galactic
git clone https://github.com/youtalk/dynamixel_control.git src
vcs import src < src/dynamixel_control.repos
rosdep install --from-paths src --ignore-src -r -y
colcon build --symlink-install --cmake-args -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
. install/setup.bash
`

error:
`
fatal error: hardware_interface/base_interface.hpp: No such file or directory
   20 | #include <hardware_interface/base_interface.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/dynamixel_hardware.dir/build.make:63: CMakeFiles/dynamixel_hardware.dir/src/dynamixel_hardware.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:78: CMakeFiles/dynamixel_hardware.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
---
Failed   <<< dynamixel_hardware [22.0s, exited with code 2]
`

**Comment by 3mrrrx** [comment]
these  the available libraries in for both galatic and foxy.


 `
ros-galactic-dynamic-edt-3d                          ros-galactic-dynamixel-sdk-custom-interfaces-dbgsym
ros-galactic-dynamic-edt-3d-dbgsym                   ros-galactic-dynamixel-sdk-dbgsym
ros-galactic-dynamixel-sdk                           ros-galactic-dynamixel-sdk-examples
ros-galactic-dynamixel-sdk-custom-interfaces         ros-galactic-dynamixel-sdk-examples-dbgsym

ros-foxy-dynamic-edt-3d                          ros-foxy-dynamixel-sdk
ros-foxy-dynamic-edt-3d-dbgsym                   ros-foxy-dynamixel-sdk-custom-interfaces
ros-foxy-dynamic-graph                           ros-foxy-dynamixel-sdk-custom-interfaces-dbgsym
ros-foxy-dynamic-graph-dbgsym                    ros-foxy-dynamixel-sdk-dbgsym
ros-foxy-dynamixel-hardware-interface            ros-foxy-dynamixel-sdk-examples
ros-foxy-dynamixel-hardware-interface-dbgsym     ros-foxy-dynamixel-sdk-examples-dbgsym
``

apperently ros-galactic-dynamixel-hardware-interface doesn't exist!!!

**Comment by 3mrrrx** [comment]
i might have made progress here by appending the dynamixel_control.repos file:

`repositories:
  dynamixel-workbench:
    type: git
    url: https://github.com/ROBOTIS-GIT/dynamixel-workbench.git
    version: ros2
  dynamixel-workbench-msgs:
    type: git
    url: https://github.com/ROBOTIS-GIT/dynamixel-workbench-msgs.git
    version: ros2
  ros2_control:
      type: git
      url: https://github.com/ros-controls/ros2_control.git
      version: foxy
`

still have to test this!

**Comment by 3mrrrx** [comment]
this wil not work and brings out the same error!

repositories:
dynamixel-workbench:
type: git
url: https://github.com/ROBOTIS-GIT/dynamixel-workbench.git
version: ros2
dynamixel-workbench-msgs:
type: git
url: https://github.com/ROBOTIS-GIT/dynamixel-workbench-msgs.git
version: ros2
ros2_control:
type: git
url: https://github.com/ros-controls/ros2_control.git
version: master


error:

 fatal error: hardware_interface/base_interface.hpp: No such file or directory
   20 | #include <hardware_interface/base_interface.hpp>

**Comment by youtalk** [comment]
I've not tested on ROS 2 Galactic yet. Please use ROS 2 Foxy first if you need it.

**Comment by 3mrrrx** [comment]
thank you for the quick relay! i will do my best to work within foxy....

**Comment by youtalk** [comment]
Thanks to @Schnilz's effort, the  https://github.com/youtalk/dynamixel_control/tree/galactic branch can be built on ROS 2 Galactic.
