### ISSUE TITLE
Could you recommend me  please .

### ISSUE THREAD

**Issue by pannatorn6395** [youtalk/dynamixel_control#33]
Could you recommend me  please , I want to read present_input_voltage  form dynamixel but i don't know main file for ros node and code for read . i need some guide

**Comment by ijnek** [comment]
I believe accessing values such as present_input_voltage, is beyond the scope of dynamixel_control. You can access such values directly from the underlying [dynamixel-workbench](https://github.com/ROBOTIS-GIT/dynamixel-workbench/tree/ros2) package.

**Comment by pannatorn6395** [comment]
thank you @ijnek
