### ISSUE TITLE
Splitting out examples to a separate repository?

### ISSUE THREAD

**Issue by ijnek** [youtalk/dynamixel_control#36]
The ``pantilt_bot_description`` and ``open_manipulator_x_description`` example packages are great, but I think it would be better split them out into a separate repository for two reasons.

1. When building from source, I often use rosdep to install package dependencies. If I want to use the dynamixel_hardware package only, I still have to clone the other two packages add an AMENT_IGNORE file to the example packages to prevent unnecessary dependencies getting installed (eg. ``realsense2_description`` is not available in rolling) and getting built. If the repositories were separate, I wouldn't have to do this.
2. When releasing the package, bloom will usually release all packages in the repository together. I'm not sure if you intend to release pantilt_bot_description and open_manipulator_x_description. The version numbers of all package numbers must be increased together.

I don't know if I can get around to doing this, but want to hear your thoughts @youtalk.

**Comment by youtalk** [comment]
It's a nice idea. I'm going to do it.

**Comment by youtalk** [comment]
Done. https://github.com/dynamixel-community/dynamixel_hardware_examples
