### ISSUE TITLE
rosdep fails on ROS 2 Rolling

### ISSUE THREAD

**Issue by ijnek** [youtalk/dynamixel_control#38]
```sh
ijnek@ijnek-MS-7924:~/tmp_workspaces/dynamixel_control_ws$ rosdep install --from-paths src --ignore-src -r -y
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
pantilt_bot_description: Cannot locate rosdep definition for [realsense2_description]
Continuing to install resolvable dependencies...
#All required rosdeps installed successfully
```

Installation instructions' rosdep fails because the realsense2_description package isn't available [in rolling](https://index.ros.org/p/realsense2_description/#rolling). I've opened a [ticket](https://github.com/IntelRealSense/realsense-ros/issues/2523) against IntelRealSense/realsense-ros to request for a release in rolling, which should solve this issue.

**Comment by youtalk** [comment]
It's time to separate packages. https://github.com/youtalk/dynamixel_control/issues/36#issuecomment-1296210939

**Comment by ijnek** [comment]
Closing, as examples have been separated out into a separate repository for Rolling onwards (https://github.com/dynamixel-community/dynamixel_hardware_examples).
