### ISSUE TITLE
Transfer repository from youtalk to dynamixel-community

### ISSUE THREAD

**Issue by youtalk** [youtalk/dynamixel_control#46]
Hi @ijnek and @ROBOTIS-Will 
Thank you for discussing releasing dynamixel_hardware package on ROSCon 2022. It was so exciting.

- [x] 1. Separate this repository into two repositories: `dynamixel_hardware` and `dyanamixel_hardware_examples` to resolve https://github.com/youtalk/dynamixel_control/issues/36
- [x] 2. Transfer their repositories to a new organization `dynamixel_community`.
- [x] 3. Make release repositories `dynamixel_hardware-release` and `dyanamixel_hardware_examples-release` on the organization.
- [x] 4. Release `dynamixel_hardware` package first!

What do you think? I want to add you to the organization's co-owners.

**Comment by ijnek** [comment]
This is great and I would be happy to be a co-owner. Thanks @youtalk!

**Comment by youtalk** [comment]
The release is ongoing! https://github.com/ros/rosdistro/pull/35400
