### ISSUE TITLE
No gripper movement

### ISSUE THREAD

**Issue by ajaysonar** [youtalk/dynamixel_control#50]
Hi,

I am using your code to test my Dynamixel openmanipulator arm. I am able to move the arm except for the gripper. I have checked all the settings including the ID numbers of the motor via Dynamixel Wizard. I can move the gripper motor via the Wizard tool so I can confirm that the motor is not an issue. Could you suggest what I can do to troubleshoot this issue.

Thanks,
Ajay

**Comment by youtalk** [comment]
I think you need to use `transmission` because the gripper value is given by the meter [m] unit but the default ros2_control value is given by the angle [rad] unit. 
This PR is my try to imitate `simple_transmission` for the gripper. https://github.com/youtalk/dynamixel_hardware/pull/11/files Please check it.

**Comment by ajaysonar** [comment]
Thank you for your feedback. I will try you suggestion.

Ajay

**Comment by ijnek** [comment]
Hi @ajaysonar, I'm going to close this out as I believe it is resolved. If now, please comment and we can re-open.

**Comment by mayank0621** [comment]
Hi I'm getting similar error, when I do these changes in humble branch, the values of gripper joint exceed the limit by a lot. It should be between -0.010 to 0.019. But when I make these changes, it reaches 108 meters. In the image below you can see the gripper is in the right top corner. It is very far away from where it should be.


@youtalk, @ijnek, @ajaysonar  Any help would be appreciated. 
![MicrosoftTeams-image](https://github.com/dynamixel-community/dynamixel_hardware/assets/98181895/05a583eb-850d-4037-a92d-de02028843b2)
