### ISSUE TITLE
Releases for iron, jazzy and rolling

### ISSUE THREAD

**Issue by ijnek** [youtalk/dynamixel_control#72]
Since jazzy release is in full throttle, now is a good time to get new changes released into rosdistro. I'm happy to make the releases some time next week. Here's a layout of things that will happen:

Iron release (0.4.0):
  * [ ] ~~Split off iron branch from 0.3.1 tag~~
  * [ ] ~~Backport any non-API breaking bug fixes from rolling to iron branch~~
  * [x] Split off iron branch from rolling
  * [x] Add branch protection rule (move to using rulesets acorss all active distros)
  * [x] Make an iron release
  * [x] Update [devel branch in rosdistro](https://github.com/ros/rosdistro/blob/8004c6218838ea3822e4e7ca397835b0817f4a2a/iron/distribution.yaml#L1084) to iron

Jazzy release (0.5.0):
* [x] Create jazzy branch
* [x] Make release, bump minor version
* [x] Update devel branch in rosdistro

Rolling release (0.6.0):
* [x] Ensure there are no changes since last release that have broken API compatibility.
* [x] Make release, bump minor version to ensure rolling version stays above jazzy

Some things that should happen after those releases:
- [ ] Jazzy CI should be added to jazzy branch (https://github.com/dynamixel-community/dynamixel_hardware/pull/85)

@youtalk Tell me if you have any issues with the above

**Comment by youtalk** [comment]
I have no issue but I've changed job last week. So I don't have enough time to do them these days. Please proceed without me if you want. Thank you!

**Comment by ijnek** [comment]
No problem, congrats on the new job! I'll try and get to this this week

**Comment by ijnek** [comment]
Since I am the only available maintainer / reviewer, I am going to allow myself to bypass reviews for my own pull requests. The one-review rule is still in place for other contributors.

**Comment by ijnek** [comment]
>  * [ ] Backport any non-API breaking bug fixes from rolling to iron branch

There were no API breaking changes, but one ABI-breaking change (#65). However, the ABI breaking change was also separately made on the humble branch (#64), so i'm going to let this one slide and have it included in the new iron branch too.

Apart from that one change, there are no major changes, but only improvements since 0.3.1 so instead of forking iron off of 0.3.1, i'm going to fork off from current rolling instead.
